repository:
    path: github.com/zhangmingkai4315/exporter-hub
build:
    binaries:
      - name: exporter-hub
    flags: -a -tags 'netgo static_build'
    ldflags: |
        -s
        -X {{repoPath}}/vendor/github.com/prometheus/common/version.Version={{.Version}}
        -X {{repoPath}}/vendor/github.com/prometheus/common/version.Revision={{.Revision}}
        -X {{repoPath}}/vendor/github.com/prometheus/common/version.Branch={{.Branch}}
        -X {{repoPath}}/vendor/github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
        -X {{repoPath}}/vendor/github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}
tarball:
    files:
        - LICENSE
        - config
crossbuild:
    platforms:
        - linux/amd64
        - linux/386