
[[constraint]]
  name = "github.com/ncabatoff/process-exporter"
  version = "0.2.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/prometheus/common"

[[constraint]]
  name = "github.com/prometheus/node_exporter"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/fvbock/endless"

[[constraint]]
  name = "github.com/prometheus/snmp_exporter"
  version = "0.9.0"
