server: 0.0.0.0
port: 10010
exporters:
  - name: node_exporter
    path: /node_exporter
    enable: true

  - name: port_exporter
    path: /port_exporter
    enable: true
    config_path: ./config/port_exporter.yml

  - name: process_exporter
    path: /process_exporter
    enable: true
    config_path: ./config/process_exporter.yml

  - name: blackbox_exporter
    path: /blackbox_exporter
    enable: true
    config_path: ./config/blackbox_exporter.yml
  
  - name: snmp_exporter
    path: /snmp_exporter
    enable: true
    config_path: ./config/snmp_exporter.yml